# TravisCI configuration for sitecrafting/sc-plugin

language: php
os:
  - linux
dist: bionic

php:
  - '7.4'

cache:
  directories:
    - '${HOME}/.composer/cache'

jobs:
  include:
    - php: '7.4'
    - name: 'Building docs'
      language: node_js
      node_js: 10
      install:
        - yarn install --frozen-lockfile
      script:
        - ./bin/build-docs.sh

    # TODO test a full bin/project-setup.sh run + lando commands

install:
  - composer install --no-interaction --prefer-dist

script:
  # TODO download WP Unit Test Suite
  #- vendor/bin/phpunit --group unit
  # TODO integration tests
  #- vendor/bin/phpunit --group integration
  - ./vendor/bin/phpcs --standard=./phpcs.xml test/unit test/integration src
  - vendor/bin/phpstan analyse
